org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=enchanteds_sodium_options
mod.name=Enchanted's Sodium Options
mod.description=Changes Sodium's video settings screen to match the style of vanilla screens better
mod.group=games.enchanted
mod.version=1.1.5
mod.license=CC BY-NC 4.0
mod.source_url=https://github.com/Enchanted-Games/enchanteds-mod-template
mod.issue_tracker=https://github.com/Enchanted-Games/enchanteds-mod-template/issues
mod.icon=assets/enchanteds_sodium_options/icon.png

deps.minecraft=[VERSIONED]
dep_str.minecraft=[VERSIONED]

deps.fabric-loader=0.18.3
dep_str.fabric-loader=>=0.18

deps.fabric-api=[VERSIONED]
dep_str.fabric-api=[VERSIONED]

deps.neoforge=[VERSIONED]

publish.dry_run=true
# Uncomment and enter modrinth or curseforge project ids to enable publishing
publish.modrinth=bd7qKEEC
#publish.curseforge=
#publish.additionalVersions=[VERSIONED]