deps.minecraft=1.21.11
dep_str.minecraft=1.21.11

deps.parchment=1.21.10:2025.10.12

deps.fabric-api=0.140.2+1.21.11
dep_str.fabric-api=>=0.140.2+1.21.11
deps.modmenu=17.0.0-alpha.1

deps.sodium_compiled_against=0.8.11
deps.sodium=0.8.11+mc1.21.11
dep_str.sodium=>0.8.4 <0.8.11

deps.iris=1.10.4+1.21.11